### ISSUE TITLE
Failed to compile error

### ISSUE THREAD

**Issue by alexc-MSFT** [tlovett1/alexa-skill-test#1]
Looks like a useful tool however trying on trying to run it i'm getting a compile error - 

Module parse failed: C:\Users\...\AppData\Roaming\npm\node_modules\alexa-skill-test\src\index.js Unexpected token (19:2)
You may need an appropriate loader to handle this file type.
|
| render(
|   <Provider store={store}>
|     <App />
|   </Provider>,
webpack: Failed to compile.

Any ideas?

Also does this tool support ES6? It seems lambda-local and node-lambda don't support it properly so this might be a good workaround for me.

**Comment by tempestn** [comment]
^ Just tried, and I'm seeing exact same issue

**Comment by tlovett1** [comment]
Hey guys, this should be fixed in 1.0.4 (on npm). Can you confirm?

**Comment by tempestn** [comment]
Working now - thanks!
